### ISSUE TITLE
the shape is not compatible

### ISSUE THREAD

**Issue by 1044197988** [ektas0330/cell-segmentation#1]
The output of your model is (None,256,256,3)
But lovasz_softmax labels: [B, H, W] Tensor, ground truth labels (between 0 and c-1)
Why does it work? Should it report an error
My model output is (None,64,64,6)
In your way, training will report errors:
Tensorflow. Python. Framework. Errors_impl. InvalidArgumentError: Incompatible shapes: [393216] vs. [65536]
[[node loss/conv2d_8_loss/sub (defined at C:\Users\Admin\Desktop\Project\train.py:153)] [Op: inference_keras_scratch_graph_16271]
The Function call stack:
keras_scratch_graph
Tip: the shape is not compatible. I think the shape of the label is wrong

**Comment by 1044197988** [comment]
通过argmax实现了形状匹配
但是loss虽然下降，准确率指标却也在下降，非常低

**Comment by ektas0330** [comment]
The shape of the label is compatible with the model output because the multi-class lovasz_softmax function interprets the model output [None,256,256,3] i.e. class probabilities at each prediction (between 0 and 1) as binary (sigmoid) output with outputs of size [B, H, W] which is same as the label shape.  Particularly, you can modify the function lovasz_softmaz_flat and it's treatment of the classes according to your use case.
